### ISSUE TITLE
Add a visualizer like Regulex

### ISSUE THREAD

**Issue by glebec** [gskinner/regexr#105] opened 2015-07-13 20:11 UTC
I think it would be awesome if you could add a pattern visualizer like [Regulex](https://jex.im/regulex/). Currently when I work on regular expressions I keep both Regulex & Regexr open and copy-paste between windows… yuck. One site which handles reference, text demoing, _and_ pattern visualization would be the holy grail of regex tools.

**Comment by Nightfirecat** [comment] 2015-07-13 22:36
Duplicate of #52.

**Comment by gskinner** [comment] 2017-08-24 15:39
Closing in favor of #52

**Closed by gskinner** 2017-08-24 15:39 UTC
