### ISSUE TITLE
Filling form arguments with URL parameters

### ISSUE THREAD

**Issue by CrazyPython** [gskinner/regexr#181] opened 2017-02-19 15:10 UTC
I'm making a shell script that does things with regexes, and I want to be able to implement a `--debug` option that opens the regex and text to be matched in regexr.

Can a system be implemented where you can prefill the two forms using URL parameters? For example, `regxr.com/?body=01234&pattern=\d+`.

**Comment by digitalica** [comment] 2017-03-02 16:54
i would like that too, to be able to use regexr for a (js/html based) presentation on regexes.

Ideally i would like to be able to give a set of sample texts, so i (or students) can easily switch between them and/or reset.

Regexr looks good and works nice by the way!

**Comment by Nightfirecat** [comment] 2017-03-02 17:38
Duplicate of #55, I believe.

**Comment by gskinner** [comment] 2017-08-24 02:51
This has been added to v3.0, in the form:
http://regexr.com?expression=foo&text=bar

It will also have support for Tool, just finalizing the naming for the tool input. Will leave this open until we launch v3.

**Comment by gskinner** [comment] 2017-08-24 02:52
Actually, going to close this as it is a duplicate of #55 (per @Nightfirecat )

**Closed by gskinner** 2017-08-24 02:52 UTC
