### ISSUE TITLE
Regex /</g selects whole HTML tag

### ISSUE THREAD

**Issue by ottoteixeira** [gskinner/regexr#154] opened 2016-06-30 13:17 UTC
A simple "/</g" is selecting 2 whole HTML tags. Looks like a bug in the highlighting.
Sample: http://regexr.com/3dnns

![regexr](https://cloud.githubusercontent.com/assets/17476/16489430/e0cd807c-3eab-11e6-989b-e85ff1d66447.png)

**Comment by wdamien** [comment] 2016-06-30 15:06
@ottoteixeira Nice find, I have not seen this before. Can you please provide your browser and OS version? I can't reproduce this with any of my browsers. Thanks!

**Comment by Nightfirecat** [comment] 2016-06-30 16:19
Ditto, can't reproduce with the example provided on FF47.0/Win7.

**Comment by ottoteixeira** [comment] 2016-06-30 16:23
I said whole HTML tag, but it's actually the whole line, not tag.
Browser: Chromium 50.0.2661.102, Ubuntu 14.04 (64-bit)

It seems to be related to the position and/or size of things.
Check these newer images. The window was resized.
![fullscreen](https://cloud.githubusercontent.com/assets/17476/16495903/be695c62-3ec5-11e6-9838-d6e7fe4b69c3.png)
![small](https://cloud.githubusercontent.com/assets/17476/16495904/be872832-3ec5-11e6-8934-152b9b8140c5.png)

**Comment by wdamien** [comment] 2016-06-30 20:58
@ottoteixeira Thanks! The window size was key here.  If I resize my Chrome 51 window to around 2050px wide I can get the long highlight, sometimes on multiple lines.

**Comment by gskinner** [comment] 2017-06-13 18:11
Is this still an issue? I've spent the last 5 minutes or so trying to repro in Chrome 58, and can't do so. I'm going to close this for now, but please reopen if it's still an issue.

**Closed by gskinner** 2017-06-13 18:11 UTC
Labels: bug

**Comment by ottoteixeira** [comment] 2017-06-13 18:25
Can't reproduce on Chrome 58.
