### ISSUE TITLE
Chrome extension

### ISSUE THREAD

**Issue by rdpascua** [gskinner/regexr#109] opened 2015-09-18 04:34 UTC
Do you have any plans adding this?

**Comment by wdamien** [comment] 2015-09-18 15:06
No we have not considered this. Can you provide more details on what you envision a Chrome extension doing?

**Comment by rdpascua** [comment] 2015-09-18 15:39
Sorry what I mean is a standalone chrome application, in which you can run regexr offline

Like postman
https://chrome.google.com/webstore/detail/postman/fhbjgbiflinjbdggehcddcbncdddomop?hl=en

**Comment by Nightfirecat** [comment] 2015-09-18 17:56
Duplicate of #26?

**Comment by gskinner** [comment] 2015-09-18 17:59
Yes. Duplicate. Closing.

**Closed by gskinner** 2015-09-18 17:59 UTC
Labels: duplicate
