### ISSUE TITLE
Highlighting doesn't work with menu expanded in v3

### ISSUE THREAD

**Issue by HankAviator** [gskinner/regexr#224] opened 2017-12-04 05:19 UTC
On Chrome 62.0.3202.94 with expanded menu ![](https://i.imgur.com/GQgsmAM.png)
menu collapsed
![](https://i.imgur.com/fkrXvvf.png)
On Edge 41.16299.15.0 ![](https://i.imgur.com/0ovKWnD.png)

Previous version works well on Chrome.

**Comment by gskinner** [comment] 2017-12-06 17:29
I'm testing in the same version of Chrome, and haven't seen this issue. Is there any chance you have any extensions that could be causing issues? Any errors in the console?

**Comment by HankAviator** [comment] 2017-12-07 05:04
> Is there any chance you have any extensions that could be causing issues?
No
> Any errors in the console?
No

Maybe you can try maximize Chrome - then all highlights are gone.

**Comment by HankAviator** [comment] 2017-12-07 05:04
> Is there any chance you have any extensions that could be causing issues?
No
> Any errors in the console?
No

Maybe you can try maximize Chrome - then all highlights are gone.

**Comment by lsze** [comment] 2018-01-04 05:50
Having the same issue in Chrome 63.0.3239.108 on Windows 10. Disabling extensions seems to make no difference. The only thing that appears to fix it is any kind of horizontal resizing of the window, whether that be by closing the Menu panel, manually dragging the window, or opening a side-docked Chrome Devtools. No errors in console btw.

It may be relevant that I am using a 4k monitor, as this issue is not present on my Windows laptop running the same version of Chrome. My resolution is set to 3840 x 2160 with 150% scaling.

**Comment by HankAviator** [comment] 2018-01-04 05:54
Mine is 3200 x 1800 with 250% scaling

**Comment by ohaucke** [comment] 2018-01-05 13:10
I've the same issue:
3840 x 2160 with 125% scaling (Operating System) in Chrome and in Firefox the initial highlighting is a bit off until i modify the value in the "Text" field
![ff](https://user-images.githubusercontent.com/3750494/34610556-f9cd004a-f221-11e7-983f-a6c89f0eca00.png)

**Comment by HankAviator** [comment] 2018-01-05 15:36
![yea](http://i0.kym-cdn.com/photos/images/original/000/107/432/i_hug_that_feel.png)

**Comment by wdamien** [comment] 2018-01-05 18:01
I can reproduce this on a 1920 x 1080 display, @ 125%.  Chrome needs to be maximized, and the menu open, for the highlights to disappear. For me it only happens when I have 2 monitors running, and the issue only appears on the monitor that is not my main display, in this case my laptop display. I cannot reproduce on my secondary monitor when using the same settings.

Windows 10 Home (1709)
Chrome 63.0.3239.84

**Comment by HankAviator** [comment] 2018-01-05 18:04
So now we've got:
* maximized window
* Chrome
* Windows (10?)
* some hd display

**Comment by gskinner** [comment] 2018-01-05 18:07
Ok. So this is almost definitely a Chrome bug then. The question is, can we work around this? I can't repro on OSX, so I'll need to fire up Basecamp and test there. Hopefully I can take a look in the next few days.

**Comment by Thesharing** [comment] 2018-01-15 07:45
Meet the same problem.

OS: Windows 10 1709
Browser: Chrome 63.0.3239.132 x64
Screen resolution: 2560*1440
Scaling: 175%

When maximizing the window and leave toolbox open, highlight will disappear.

**Comment by hmol** [comment] 2018-01-23 09:42
I also encountered the same problem 
Browser: Chrome Version 63.0.3239.132 (Official Build) (64-bit)
Screen resolution: 1920x1080
OS: Windows 10
Scaling: 100%

**Comment by HankAviator** [comment] 2018-01-23 10:00
@hmol would you please confirm if it happens only when the window is maximised?

**Comment by hmol** [comment] 2018-01-23 10:18
yes, confirmed!

**Comment by Sylphony** [comment] 2018-01-26 23:14
> When maximize the window and leave toolbox open, highlight will disappear.

This was exactly it!  Thanks for bringing it up - so glad I can use this tool again.

**Comment by gskinner** [comment] 2018-06-08 17:05
Is this still an issue in newer versions of Chrome?

**Comment by HankAviator** [comment] 2018-06-08 17:06
yes, it persists on Chrome 67.0.3396.79

**Comment by gskinner** [comment] 2018-11-02 16:29
Ok. I was finally able to reproduce this on my system, and I'm it here for future reference:
- Windows 10
- switch to 2560x1440 (on my 3440x1440 external monitor)
- 150% scaling in the OS, 100% in browser
- browser window maximized

Alternatively (same as above, but with):
- 100% scaling in the OS, 125% in browser

Alternatively:
- same 100/125, but at 3440x1440, and resize the browser horizontally until the highlights disappear
- ex. 2639 x 1359 works

Based on this, my immediate guess is some kind of rounding / math error either in our highlighting code, or in CodeMirror's text metric methods.

**Comment by gskinner** [comment] 2018-11-02 16:31
Note that vertical size doesn't seem to matter, unless it causes a change in the horizontal size of the Text area.

**Comment by gskinner** [comment] 2018-11-02 17:28
Ok. The issue here appears to be that at certain scales and dimension Chrome will return a width for our resize detector that will cause the parent container to show a scrollbar if the canvas is set to that width. This leads to another resize triggering, which resizes the canvas, which hides the scrollbar.

This resize loop is what was resulting in the highlights disappearing.

I found two fixes for this: `overflow:hidden` on the parent, or sizing the canvas 1px smaller. The latter seems more fragile and arbitrary, so I am going with the CSS solution.

This appears to be fixed locally. I will leave this issue open for the moment, and ask for help testing when I push it live.

**Comment by gskinner** [comment] 2018-11-02 18:55
This fix has been pushed live in the v3.5.3 update. Please test and let us know if there are any lingering problems.

**Closed by gskinner** 2018-11-02 18:55 UTC
Labels: bug

**Comment by max810** [comment] 2018-11-06 19:21
I confirm, everything is working properly know, both in fullscreen/window adn with/without side menu.
