### ISSUE TITLE
Add support for ICU engine

### ISSUE THREAD

**Issue by rajohns08** [gskinner/regexr#164] opened 2016-10-11 18:05 UTC
Add support for the [ICU](http://userguide.icu-project.org/strings/regexp) regex engine. Used by [Foundation](https://en.wikipedia.org/wiki/Foundation_Kit) for all iOS and macOS development.

**Comment by Nightfirecat** [comment] 2016-10-11 19:45
Duplicate of #32.

**Closed** 2016-10-28 15:09 UTC
