### ISSUE TITLE
Add Support for R Language??

### ISSUE THREAD

**Issue by pgensler** [gskinner/regexr#177] opened 2017-01-13 23:07 UTC
Not sure if I am the only one, but I think it would be extremely helpfull to add support for the R Language to the regex tester. I have been trying to find a good tester, and think it would be extremely helpful to use this platform to share with others some simple code used. As an example:

'400,BLOCK 17TH ST, 5TH FL'

Matching  the comma in this string can be a bit difficult knowing that you have to escape characters in R to process it correctly. Thanks.

**Comment by Nightfirecat** [comment] 2017-01-13 23:20
Duplicate of #32.

**Closed** 2017-06-13 17:55 UTC
