### ISSUE TITLE
adding support for multiple languages

### ISSUE THREAD

**Issue by Data-Base** [gskinner/regexr#166] opened 2016-10-28 10:35 UTC
would be nice to have the possibility to generate regex that suit different languages like in this link [http://emailregex.com/](emailregex.com)

I use your site to build and test regex but i'm trying to use it with PL/SQL and it's not working out of the box!

cheers,

**Comment by lannymcnie** [comment] 2016-10-28 15:07
Duplicate of #32

**Closed** 2016-10-28 15:08 UTC
