### ISSUE TITLE
Display helpful diagram of the regex

### ISSUE THREAD

**Issue by pabloab** [gskinner/regexr#145] opened 2016-04-04 03:32 UTC
Please consider adding a helpful diagram about whats going on, like what show on
https://regexper.com Source code available on https://github.com/javallone/regexper-static

**Comment by Nightfirecat** [comment] 2016-04-04 06:37
Duplicate of #52.

**Comment by pabloab** [comment] 2016-04-06 15:56
Thank you @Nightfirecat. Sad to see the core team think adding regexper feature is pointless. Hopefully you will change your mind. Meantime I'll keep recommending two sites instead of one for people trying to learn and practice regular expressions :(

**Comment by lannymcnie** [comment] 2016-04-06 16:05
In the latest version, published in the last few months, there is a bunch of tools that provide details and explanation of patterns. While it isn't the visual diagram, it at least provides a great outline of patterns and matches.

![screen shot 2016-04-06 at 10 04 13 am](https://cloud.githubusercontent.com/assets/590731/14323730/f95c02fe-fbde-11e5-9211-cd3848a9102c.png)

**Comment by gskinner** [comment] 2017-08-24 03:33
Is there still a desire for a visual chart? If so, what does it offer beyond the "Explain" tab. Please reopen as appropriate.

**Closed by gskinner** 2017-08-24 03:33 UTC
Labels: enhancement
