### ISSUE TITLE
Inconsistent result compared with JS in specific case

### ISSUE THREAD

**Issue by mesqueeb** [gskinner/regexr#275] opened 2018-07-18 05:16 UTC
Case:
regex = `/(.+)\/([^\/]+)\.([^\.]+$)/g`
text = `src/index.js`

Your website gives `index` for group 2.

JavaScript: `text.replace(regex, '$2')` gives `index.`

**Comment by stefnotch** [comment] 2018-08-22 14:20
Cannot reproduce (Tested in Firefox 61, Chrome 68, Edge 42, IE 11)
```javascript
> "src/index.js".replace(/(.+)\/([^\/]+)\.([^\.]+$)/g, '$2')

"index"
```

**Comment by gskinner** [comment] 2018-08-22 16:40
Thanks for testing @stefnotch ! I'm seeing the same results here. Also, given that RegExr uses the browser's RegExp engine directly, it's not likely that it would return different results when using the JS flavor.

Closing for now. Please reopen if you can reproduce this and provide additional information.

**Closed by gskinner** 2018-08-22 16:40 UTC
