### ISSUE TITLE
"Insert" key (overwrite mode) allows you to overwrite open/close and flags

### ISSUE THREAD

**Issue by Krenair** [gskinner/regexr#96] opened 2015-05-19 12:07 UTC
Causing various strange issues. You can insert characters which RegExr thinks are open/close or flags and shows them as such in the popup, but they are not coloured.

**Comment by wdamien** [comment] 2015-05-19 15:32
Duplicate of #18 (Feel free to add more information to the other bug, if anything is missing)

**Closed by wdamien** 2015-05-19 15:32 UTC
